[build]
  command = "npm run build"
  publish = "dist"

[security]
  # Indique à Netlify que ces variables sont publiques par design
  limit_secrets_scanning = true
  
  [security.secrets_scanning]
    # Liste des variables à ignorer
    allowed_secrets = ["VITE_SUPABASE_URL", "VITE_SUPABASE_ANON_KEY"]