name: Backup Supabase Live

on:
  workflow_dispatch: # C'est ce qui crÃ©e le bouton pour tester direct

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Install DB client
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17

      - name: Run dump
        run: pg_dump "${{ secrets.DB_URL }}" > backup.sql

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mon-backup-db
          path: backup.sql
